### ISSUE TITLE
Scraper not returning anything

### ISSUE THREAD

**Issue by kkcastizo** [dtrungtin/actor-allrecipes-scraper#11]
I tried using the actor with a few different URLs such as: https://allrecipies.com/recipes and https://www.allrecipes.com/recipes/17674/main-dish/soups-and-stews/. Search text was kept empty, and max items from 250 - 1000. But it returned nothing every time. The link to the log is below.

https://api.apify.com/v2/logs/IpmPxcBBJzYscreLX

**Comment by pocesar** [comment]
@kkcastizo thanks for the report, this has been fixed
