### ISSUE TITLE
Search doesn't work properly

### ISSUE THREAD

**Issue by metalwarrior665** [dtrungtin/actor-allrecipes-scraper#14]
{
  "searchText": "vindaloo",
  "extendOutputFunction": "($, pageResult) => {\n  return {}\n}",
  "proxyConfiguration": {
    "useApifyProxy": false
  }
}

Porduces 76k results but manual search only 12

**Comment by dtrungtin** [comment]
Fixed. https://github.com/dtrungtin/actor-allrecipes-scraper/commit/6b774641fcc0de6d302cc830caff4be8672c81c9

**Comment by zpelechova** [comment]
fixed 05/21
