### ISSUE TITLE
When input urls are taken from CSV /Google sheet, no info about the actual url being scraped in the log.

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-allrecipes-scraper#17]
https://my.apify.com/view/runs/f6zOaRhnvhi4vdh8Z

**Comment by zpelechova** [comment]
Where in the log is it then? https://my.apify.com/view/runs/Pi7jO9B4HuHC7ddMO

**Comment by dtrungtin** [comment]
Please retry in latest build.
https://my.apify.com/view/runs/7tRWX7SlaHGfMf63o

The log is 2021-08-04T06:28:37.132Z INFO  Open url (item): https://www.allrecipes.com/recipe/228443/authentic-pho/

**Comment by zpelechova** [comment]
fixed 09/2021
